### ISSUE TITLE
Adding users via group admin gives admin then removes it

### ISSUE THREAD

**Issue by Railworks2** [SyncAdmin/Plugins#37] opened 2017-11-24 11:03 UTC
Issue: Users who are given any level of permission via the group admin options within the settings are given it but instantly taken away.

Repo:

Admin POV
- Add a group to the admin (Settings.Group.Group Permissions)
- Save as normal

User POV
- Observe SA notifications

--------------------------------------

Expected result: Users are given admin as normal
Actual result: Users are given admin with the respective notifications, instantly after that it shows that you have been given user permissions (level 0)
![image](https://user-images.githubusercontent.com/27024242/33207690-8429ba68-d106-11e7-85b2-b3afeb4c54f2.png)
--------------------------------------

Unknown SA version; Game IDs which have been reported in [1186982515](https://www.roblox.com/games/1186982515/Sip-N-Chill-Cafe) and [1180891150](https://www.roblox.com/games/1180891150/Sip-N-Chill-Interview-Center-V1)
-------------------------------------

Issue reported by Ericscarfone (SA partner) via Discord

**Comment by ForPizzaSake** [comment] 2017-11-24 15:56
After testing on my own game, I cannot reproduce this bug with group admin settings.

I'm closing this issue, however, please re-open it if the problem persists - preferable with a repro.

**Closed by ForPizzaSake** 2017-11-24 15:56 UTC
