### ISSUE TITLE
Unbanning a group in the settings command fails.

### ISSUE THREAD

**Issue by Railworks2** [SyncAdmin/Plugins#2] opened 2017-07-15 18:55 UTC
When attempting to unban a group using the settings GUI, though both "apply" and "close and save" options, the ban is not revoked. 

This is both physically and visually.

**Comment by DataSynchronized** [comment] 2017-07-15 19:09
Hey there,

Thanks for reporting this bug to us. Do you have any steps on how we could repro this bug or does this apply to any game regardless of conditions? 

Thanks!

**Comment by Railworks2** [comment] 2017-07-15 20:13
- Have a banned group in settings by any mean.
- Unban the group by normal by any means using the settings
- Visually check the group is unbanned
- Check the group is unbanned

**Comment by DataSynchronized** [comment] 2017-07-15 20:14
Thanks, we will investigate this issue. Does this apply to a specific game or does this apply to all games running the same version of SyncAdmin?

**Comment by Railworks2** [comment] 2017-07-15 20:16
I suspect all games, this is due to an user report requesting support on Discord and also during testing.
I also suspect all games due to an event with yourself involving **REDACTED** and the repeated updates regarding **REDACTED**

**Comment by DataSynchronized** [comment] 2017-07-15 20:17
Thanks for the information. We'll keep you updated on the issue.

**Comment by mathhhew** [comment] 2017-07-15 20:18
i get this too

**Comment by Railworks2** [comment] 2017-07-15 20:18
OK.

**Comment by DataSynchronized** [comment] 2017-07-15 20:20
@mathhhew Can you link us to the game which you're experiencing this issue?

**Comment by mathhhew** [comment] 2017-07-15 20:22
https://www.roblox.com/games/685549905/True-Colors-Caverns

I had to remove our settings token to get the groups unbanned so now I no longer have the issue or settings token but yeah.

**Comment by Railworks2** [comment] 2017-07-15 20:24
@DataSynchronized The same for my testing place, in which I banned @VolcanoINC 's airline as a test.
https://www.roblox.com/games/432409487/Office

**Comment by DataSynchronized** [comment] 2017-07-15 20:27
Thanks @Railworks2 and @mathhhew for your links. We'll investigate the issue further.

@mathhhew We'll look into the settings token issues. I am aware currently that the current settings system does have a lot of issues regarding sending and retrieving large amounts of information - such as large ban lists, etc.

This might be the cause of the issue you was having. We're working on improving the back-end architecture to better deal with these types of requests by breaking down the current information storage into smaller sections.

**Comment by mathhhew** [comment] 2017-07-15 20:29
ok! thanks. :)

**Comment by DataSynchronized** [comment] 2017-07-30 22:44
Hey there,

Just posting updates related to this issue. We've figured out the cause of the issue and we're working to release updates to our back-end servers to fix this issue in a new release.

If your game is currently suffering from this issue and would like a group removed, please post your GameId - _or if you're using a settings token, the last 5 characters of your settings token_ - along with the GroupId you'd like us to remove.

We will remove them for you within 24 to 48 hours after your request.

Thank you and sorry for any inconvenience caused.

**Comment by ForPizzaSake** [comment] 2017-12-05 04:54
I'm going to close this issue as we're working on a fix in the new version.

**Closed by ForPizzaSake** 2017-12-05 04:54 UTC
Labels: bug
